services:
  new:
    container_name: pryder
    image: phpmyadmin
    ports:
      - 90:90
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: ammar
      PMA_PASSWORD: 123
    depends_on:
      - mysql

  mysql:
    container_name: bckend
    image: mysql
    restart: always
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: ammar
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - 3306:3306
